// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhduqvxuhdrhwatryscc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZHVxdnh1aGRyaHdhdHJ5c2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODI1NDEsImV4cCI6MjA2OTA1ODU0MX0.AePyKJhQ3mDupo9L-f0pPS0QEl8-YJfIxG_WnLSAGrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});